version: 2
jobs:
  clj:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-21.0
    steps:
      - checkout
      - restore_cache:
          key: clj-{{ checksum "deps.edn" }}
      - run: clojure -J-Dtest -J-Dguardrails.mode=:all -A:dev:daemon:test:system-test:clj-tests
      - save_cache:
          paths:
            - ~/.m2
          key: clj-{{ checksum "deps.edn" }}
workflows:
  version: 2
  fullstack:
    jobs:
      - clj
