== Maven

== Maven Repo

=== Download Access

The maven repo for DOWNLOAD use is:

`https://mvn.fulcrologic.com`

It uses auth which is stored in a postgresql database. The username for that database
is grp, and the table is users. We will need to write an admin app that can run
to maintain this db. Users must have a username/password in this database
in order to use the repo.


Deps:

[source, clojure]
-----
{:mvn/repos {"fulcrologic" {:url "https://mvn.fulcrologic.com"}}
 ...}
-----

And in `~/.m2/settings.xml`:

[source, xml]
-----

<settings>
    <servers>
        <server>
            <id>fulcrologic</id>
            <username>tony@fulcrologic.com</username>
            <password>password</password>
        </server>
    </servers>
</settings>
-----

=== Upload Access

Auth is controlled by `/etc/nginx/mvn.htpasswd`. The upload URL is `https://mvn.fulcrologic.com/mvn`. The pom.xml
contains the right distro settings in GRP.

Add the proper credentials in `settings.xml`.

[source, xml]
-----
<settings>
    <servers>
        <server>
            <id>fulcrologic-publish</id>
            <username>tony@fulcrolog.com</username>
            <password>publish password</password>
        </server>
    </servers>
</settings>
-----

== Deploying a New Version

. Update pom.xml and pom-daemon.xml. Use `clj -Spom` to update deps in pom, and make sure version is what you want.
. Use Makefile to build/deploy the jars:

[source, bash]
-----
make deploy-checker
make deploy-daemon
-----

== Build and Deploy User Guide

Edit the adoc file(s), and use the Makefile. You will need asciidoctor installed, along with ditaa.

[source, bash]
-----
make publish
-----